// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmhLun8MrOZJANF8kEFVLEsevbtWe0x4I',
    appId: '1:64193540272:web:ee797e9af7bc35a371cb75',
    messagingSenderId: '64193540272',
    projectId: 'church-attendance-cdb07',
    authDomain: 'church-attendance-cdb07.firebaseapp.com',
    storageBucket: 'church-attendance-cdb07.firebasestorage.app',
    measurementId: 'G-ZZJDFCW88W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByTzLfyiDfNJgRpEpRCcyFmT0u9O6kUmU',
    appId: '1:64193540272:android:86bc95a548e3b53971cb75',
    messagingSenderId: '64193540272',
    projectId: 'church-attendance-cdb07',
    storageBucket: 'church-attendance-cdb07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFszOBwIYT3vlWBnyuoDxxVBmp86gDXgI',
    appId: '1:64193540272:ios:fe7d678bd44790ae71cb75',
    messagingSenderId: '64193540272',
    projectId: 'church-attendance-cdb07',
    storageBucket: 'church-attendance-cdb07.firebasestorage.app',
    iosBundleId: 'com.example.churchAttendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFszOBwIYT3vlWBnyuoDxxVBmp86gDXgI',
    appId: '1:64193540272:ios:fe7d678bd44790ae71cb75',
    messagingSenderId: '64193540272',
    projectId: 'church-attendance-cdb07',
    storageBucket: 'church-attendance-cdb07.firebasestorage.app',
    iosBundleId: 'com.example.churchAttendance',
  );
}
